#############################################################################
# Makefile for building: CoinFlip.app/Contents/MacOS/CoinFlip
# Generated by qmake (3.1) (Qt 6.5.0)
# Project:  CoinFlip.pro
# Template: app
# Command: /Users/areay7/Qt/6.5.0/macos/bin/qmake -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers -I../../../Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.5.0/macos/mkspecs/macx-clang -F/Users/areay7/Qt/6.5.0/macos/lib
QMAKE         = /Users/areay7/Qt/6.5.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/areay7/Qt/6.5.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/areay7/Qt/6.5.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CoinFlip1.0.0
DISTDIR = /Users/areay7/QtCode/QtProject/CoinFlip/.tmp/CoinFlip1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/areay7/Qt/6.5.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/areay7/Qt/6.5.0/macos/lib -framework QtMultimedia -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtNetwork -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = chooselevelscene.cpp \
		dataconfig.cpp \
		main.cpp \
		mainscence.cpp \
		mycoin.cpp \
		mypushbutton.cpp \
		playscene.cpp qrc_res.cpp \
		moc_chooselevelscene.cpp \
		moc_dataconfig.cpp \
		moc_mainscence.cpp \
		moc_mycoin.cpp \
		moc_mypushbutton.cpp \
		moc_playscene.cpp
OBJECTS       = chooselevelscene.o \
		dataconfig.o \
		main.o \
		mainscence.o \
		mycoin.o \
		mypushbutton.o \
		playscene.o \
		qrc_res.o \
		moc_chooselevelscene.o \
		moc_dataconfig.o \
		moc_mainscence.o \
		moc_mycoin.o \
		moc_mypushbutton.o \
		moc_playscene.o
DIST          = ../../../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		../../../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/lex.prf \
		CoinFlip.pro chooselevelscene.h \
		dataconfig.h \
		mainscence.h \
		mycoin.h \
		mypushbutton.h \
		playscene.h chooselevelscene.cpp \
		dataconfig.cpp \
		main.cpp \
		mainscence.cpp \
		mycoin.cpp \
		mypushbutton.cpp \
		playscene.cpp
QMAKE_TARGET  = CoinFlip
DESTDIR       = 
TARGET        = CoinFlip.app/Contents/MacOS/CoinFlip

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/areay7/QtCode/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/areay7/QtCode/QtProject/CoinFlip/CoinFlip.pro


include /Users/areay7/Qt/6.5.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

CoinFlip.app/Contents/MacOS/CoinFlip: ui_mainscence.h $(OBJECTS)  
	@test -d CoinFlip.app/Contents/MacOS/ || mkdir -p CoinFlip.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CoinFlip.pro ../../../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.5.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.5.0/macos/mkspecs/features/spec_post.prf \
		../../.qmake.stash \
		../../../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.5.0/macos/mkspecs/features/lex.prf \
		CoinFlip.pro \
		res.qrc \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.5.0/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../Qt/6.5.0/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.5.0/macos/mkspecs/features/device_config.prf:
../../../Qt/6.5.0/macos/mkspecs/common/unix.conf:
../../../Qt/6.5.0/macos/mkspecs/common/mac.conf:
../../../Qt/6.5.0/macos/mkspecs/common/macx.conf:
../../../Qt/6.5.0/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.5.0/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.5.0/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.5.0/macos/mkspecs/common/clang.conf:
../../../Qt/6.5.0/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.5.0/macos/mkspecs/qconfig.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.5.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.5.0/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.5.0/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.5.0/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.5.0/macos/mkspecs/features/spec_post.prf:
../../.qmake.stash:
../../../Qt/6.5.0/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.5.0/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.5.0/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.5.0/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.5.0/macos/mkspecs/features/default_post.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.5.0/macos/mkspecs/features/qml_debug.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.5.0/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.5.0/macos/mkspecs/features/permissions.prf:
../../../Qt/6.5.0/macos/mkspecs/features/qt.prf:
../../../Qt/6.5.0/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.5.0/macos/mkspecs/features/resources.prf:
../../../Qt/6.5.0/macos/mkspecs/features/moc.prf:
../../../Qt/6.5.0/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.5.0/macos/mkspecs/features/uic.prf:
../../../Qt/6.5.0/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.5.0/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.5.0/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.5.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.5.0/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.5.0/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.5.0/macos/mkspecs/features/yacc.prf:
../../../Qt/6.5.0/macos/mkspecs/features/lex.prf:
CoinFlip.pro:
res.qrc:
../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Resources/QtMultimedia.prl:
../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.5.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.5.0/macos/lib/QtNetwork.framework/Resources/QtNetwork.prl:
../../../Qt/6.5.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CoinFlip.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

CoinFlip.app/Contents/PkgInfo: 
	@test -d CoinFlip.app/Contents || mkdir -p CoinFlip.app/Contents
	@$(DEL_FILE) CoinFlip.app/Contents/PkgInfo
	@echo "APPL????" > CoinFlip.app/Contents/PkgInfo
CoinFlip.app/Contents/Resources/empty.lproj: 
	@test -d CoinFlip.app/Contents/Resources || mkdir -p CoinFlip.app/Contents/Resources
	@touch CoinFlip.app/Contents/Resources/empty.lproj
	
CoinFlip.app/Contents/Info.plist: 
	@test -d CoinFlip.app/Contents || mkdir -p CoinFlip.app/Contents
	@$(DEL_FILE) CoinFlip.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../Qt/6.5.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,Areay.CoinFlip,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},Areay.CoinFlip,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,logo.icns,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},logo.icns,g" -e "s,@EXECUTABLE@,CoinFlip,g" -e "s,@LIBRARY@,CoinFlip,g" -e "s,\$${EXECUTABLE_NAME},CoinFlip,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >CoinFlip.app/Contents/Info.plist
CoinFlip.app/Contents/Resources/logo.icns: logo.icns
	@test -d CoinFlip.app/Contents/Resources/ || mkdir -p CoinFlip.app/Contents/Resources/
	@$(DEL_FILE) CoinFlip.app/Contents/Resources/logo.icns
	@$(COPY_FILE) logo.icns CoinFlip.app/Contents/Resources/logo.icns

all: Makefile \
		CoinFlip.app/Contents/PkgInfo \
		CoinFlip.app/Contents/Resources/empty.lproj \
		CoinFlip.app/Contents/Info.plist \
		CoinFlip.app/Contents/Resources/logo.icns CoinFlip.app/Contents/MacOS/CoinFlip

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents chooselevelscene.h dataconfig.h mainscence.h mycoin.h mypushbutton.h playscene.h $(DISTDIR)/
	$(COPY_FILE) --parents chooselevelscene.cpp dataconfig.cpp main.cpp mainscence.cpp mycoin.cpp mypushbutton.cpp playscene.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainscence.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CoinFlip.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		../../../Qt/6.5.0/macos/libexec/rcc \
		res/OtherSceneBg.png \
		res/Coin0002.png \
		res/LevelIcon.png \
		res/Coin0001.png \
		res/LevelWinSound.wav \
		res/Coin0004.png \
		res/LevelCompletedDialogBg.png \
		res/Coin0006.png \
		res/Coin0007.png \
		res/ConFlipSound.wav \
		res/Coin0005.png \
		res/BoardNode.png \
		res/Title.png \
		res/PlayLevelSceneBg.png \
		res/BackButtonSelected.png \
		res/MenuSceneBg.png \
		res/MenuSceneStartButton.png \
		res/BackButtonSound.wav \
		res/Coin0003.png \
		res/Coin0008.png \
		res/TapButtonSound.wav \
		res/BackButton.png
	/Users/areay7/Qt/6.5.0/macos/libexec/rcc -name res --no-zstd res.qrc -o qrc_res.cpp

compiler_moc_header_make_all: moc_chooselevelscene.cpp moc_dataconfig.cpp moc_mainscence.cpp moc_mycoin.cpp moc_mypushbutton.cpp moc_playscene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chooselevelscene.cpp moc_dataconfig.cpp moc_mainscence.cpp moc_mycoin.cpp moc_mypushbutton.cpp moc_playscene.cpp
moc_chooselevelscene.cpp: chooselevelscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		playscene.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib chooselevelscene.h -o moc_chooselevelscene.cpp

moc_dataconfig.cpp: dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib dataconfig.h -o moc_dataconfig.cpp

moc_mainscence.cpp: mainscence.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		chooselevelscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		playscene.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib mainscence.h -o moc_mainscence.cpp

moc_mycoin.cpp: mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		playscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		mycoin.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib mycoin.h -o moc_mycoin.cpp

moc_mypushbutton.cpp: mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib mypushbutton.h -o moc_mypushbutton.cpp

moc_playscene.cpp: playscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		playscene.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/libexec/moc
	/Users/areay7/Qt/6.5.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=13 -D__clang_minor__=1 -D__clang_patchlevel__=6 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/areay7/Qt/6.5.0/macos/mkspecs/macx-clang -I/Users/areay7/QtCode/QtProject/CoinFlip -I/Users/areay7/Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtWidgets.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtGui.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtNetwork.framework/Headers -I/Users/areay7/Qt/6.5.0/macos/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/areay7/Qt/6.5.0/macos/lib playscene.h -o moc_playscene.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainscence.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainscence.h
ui_mainscence.h: mainscence.ui \
		../../../Qt/6.5.0/macos/libexec/uic
	/Users/areay7/Qt/6.5.0/macos/libexec/uic mainscence.ui -o ui_mainscence.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

chooselevelscene.o: chooselevelscene.cpp chooselevelscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		playscene.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chooselevelscene.o chooselevelscene.cpp

dataconfig.o: dataconfig.cpp dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataconfig.o dataconfig.cpp

main.o: main.cpp mainscence.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		chooselevelscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		playscene.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainscence.o: mainscence.cpp mainscence.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/QMediaPlayer \
		../../../Qt/6.5.0/macos/lib/QtMultimedia.framework/Headers/qmediaplayer.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		chooselevelscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		playscene.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h \
		ui_mainscence.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainscence.o mainscence.cpp

mycoin.o: mycoin.cpp mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		playscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mycoin.o mycoin.cpp

mypushbutton.o: mypushbutton.cpp mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mypushbutton.o mypushbutton.cpp

playscene.o: playscene.cpp playscene.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QDebug \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QMenuBar \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qmenubar.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPainter \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QTimer \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QPropertyAnimation \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qpropertyanimation.h \
		mypushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		../../../Qt/6.5.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qevent.h \
		mycoin.h \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/QPixmap \
		../../../Qt/6.5.0/macos/lib/QtGui.framework/Headers/qpixmap.h \
		dataconfig.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QObject \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QMap \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/QVector \
		../../../Qt/6.5.0/macos/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playscene.o playscene.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_chooselevelscene.o: moc_chooselevelscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chooselevelscene.o moc_chooselevelscene.cpp

moc_dataconfig.o: moc_dataconfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataconfig.o moc_dataconfig.cpp

moc_mainscence.o: moc_mainscence.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainscence.o moc_mainscence.cpp

moc_mycoin.o: moc_mycoin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mycoin.o moc_mycoin.cpp

moc_mypushbutton.o: moc_mypushbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mypushbutton.o moc_mypushbutton.cpp

moc_playscene.o: moc_playscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playscene.o moc_playscene.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/CoinFlip/bin || mkdir -p $(INSTALL_ROOT)/opt/CoinFlip/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app
	
	$(QINSTALL) CoinFlip.app $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CoinFlip/bin/CoinFlip.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/CoinFlip/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

